config/routes.rb
    members: %w{
    },
    collections: %w{
    get _batch_add_extracts_to_batch
    get _batch_add_extracts_to_batch_via_confidence
    get _batch_add_extracts_to_batch_via_tags
    get batch_pcr
    get list_by_scope
    get list_in_range
    post _add_extract_to_batch
    post _remove_extract_from_batch
    post _worksheet
    post list_in_range
  }
  },

  'phenotypes' => {
    members: %w{
  },
    collections: %w{
    get edit
    get new_concrete_phenotype
    get new_differentia
    get new_term
    post create_composition
    post create_term
    post remove_ontology_value
    post update_count_phenotype
    post update_presence_absence_phenotype
    post update_qualitative_phenotype
    post update_relative_phenotype
  }
  },

  'primers' => {
    members: %w{},
    collections: %w{
    get show_by_gene
  }
  },

  'protocols' => {
    members: %w{
    post add_step
    post remove_step
  },
    collections: %w{}
  },

  'public_contents' => {
    members: %w{},
    collections: %w{
    post unpublish
  }
  },

  'refs' => {
    members: %w{
  get auto_complete_for_ref_other_projs
  get endnote_batch_verify_or_create
  get link_search
  get ocr_text
  get show_associations
  get show_distributions
  get show_sensus
  post _count_labels
  post create_tags_for_all_parts
  post delete_pdf
  post destroy_author
  post endnote_batch_verify_or_create
  post replace
  },
  collections: %w{
   get add
   get endnote
   get list_by_author
   get list_by_scope
   post add
   post sort_authors
   post update_all_proj_display_names
  }
  },

  'repositories' => {
    members: %w{},
    collections: %w{}
  },

  'sensus' => {
    members: %w{},
    collections: %w{
    get batch_load
    get batch_verify_or_create
    post batch_verify_or_create
    post sort_sensus
  }
  },

  'seqs' => {
    members: %w{
    },
    collections: %w{
    get create_multiple
    get list_by_scope
    get new_from_table
    get seqs_as_fasta_file
    get seqs_as_nexus
    get seqs_as_oneline
    get seqs_from_FASTA
    get summarize
    get verify_seqs_from_FASTA
    get view_query
    post _batch_add_FASTA
  }
  },

  'serials' => {
    members: %w{},
    collections: %w{
    get _add_ref_to_proj
    get _download_biostor
    get _show_params
    get find_many
    get match
    get show_all_refs
  }
  },

  'specimens' => {
    members: %w{
    get accordion
    get show_seqs
    get test
    post clone
    post destroy_determination
    post destroy_identifier
    post destroy_type_assignment
  },
  collections: %w{
   get batch_load
   get batch_verify_or_create
   get group
   get group_result_update
   get identifier_search
   get list_all
   get list_by_creator
   get list_by_current_user
   get list_by_id
   get quick_new
   post batch_verify_or_create
   post quick_create
   post search_by_identifier
  }
  },

  'standard_view_groups' => {
    members: %w{
   post add_standard_view
   post remove_standard_view
  },
  collections: %w{}
  },

  'standard_views' => {
    members: %w{},
    collections: %w{}
  },

  'tags' => {
    members: %w{
  get _popup_info
  post in_place_notes_update
  post set_tag_notes
  },
  collections: %w{
  get  list_by_keyword
  }
  },

  'taxon_hists' => {
    members: %w{},
    collections: %w{}
  },

  'taxon_names' => {
    members: %w{
    get download_taxon_name_report
    get report_ITIS_dump
    get report_taxon_names
    get show_all_children
    get show_images
    get show_immediate_child_otus
    get show_material
    get show_summary
    get show_taxonomic_history
    get show_type_material
    get test
    post add_type
    post remove_type
  },
    collections: %w{
    get batch_load
    get batch_verify
    get search
    get search_list
    get visibility
    post batch_create
    post rebuild_cached_display_name
    post toggle_public
  }
  },

  'trees' => {
    members: %w{
    get _select_node
    get phylowidget
    get show_nested_set
    get show_phylowidget
    get test
    get test2
  },
    collections: %w{
  }
  },

  } # end PRIVATE_RESOURCES

  PUBLIC_RESOURCES = {
  'associations' => {
    members: %w{},
    collections: %w{
    get browse
    get browse_by_confidence
    get browse_by_object_relationship
    get browse_by_otu
    get browse_by_ref
    get browse_by_taxon_name
    get browse_by_year
    get browse_chronological
    get browse_confidences
    get browse_negatives
    get browse_object_relationships
    get browse_otus
    get browse_refs
    get browse_show
    get browse_taxon_names
    get browse_unsupported
    get browse_untied
    get conditional
  },
  },

  'blog' => {
    members: %w{},
    collections: %w{
    get otu_page
  },
  },

  'chrs' => {
    members: %w{},
    collections: %w{
  },
  },

  'claves' => {
    members: %w{},
    collections: %w{
  },
  },

  'images' => {
    members: %w{},
    collections: %w{
  },
  },

  'labels' => {
    members: %w{},
    collections: %w{
    get list_all
    get show_via_name
  },
  },

  'multikey' => {
    members: %w{
    get _close_popup_figs
    get _cycle_elim_chr_txt_choices
    get _cycle_elim_otu_txt_choices
    get _cycle_remn_chr_txt_choices
    get _cycle_remn_otu_txt_choices
    get _popup_figs_for_chr
    get _popup_figs_for_state
    get _show_figures_for_chr
    get _update_otu_for_compare
    get add_state
    get check_for_bot_formatted_links_and_return_404s
    get choose_otu
    get conditional
    get remove_state
    get reset
    get return_chr
    get return_otu
    get show_chosen_figures
    get show_chosen_states
    get show_compare
    get show_default
    get show_otu_by_chr
    get show_remaining_figures
  },
    collections: %w{
  },
  },


  'multikey_simple' => {
    members: %w{
    get _close_popup_figs
    get _popup_figs_for_chr
    get _popup_figs_for_state
    get _update_otu_for_compare
    get add_state
    get check_for_bot_formatted_links_and_return_404s
    get choose_otu
    get remove_state
    get reset
    get return_chr
    get return_otu
    get show_chosen_states
    get show_compare
    get show_default
    get show_otu_by_chr
  },
    collections: %w{
  },
  },


  'mxes' => {
    members: %w{
  get current_cycle
  get cycle
  get grid_coding_params
  get reset_cycle
  get set_export_variables
  get show_ascii
  get show_chrs
  get show_grid_coding
  get show_grid_tags
  get show_nexus
  get show_otus
  get show_phylowidget
  get show_tnt
  get show_trees
  get simple_format
  get tnt_as_file
  },
    collections: %w{
  },
  },

  'news' => {
    members: %w{},
    collections: %w{
  },
  },

  'ontology_classes' => {
    members: %w{},
    collections: %w{
   post auto_complete_for_ontology_class
   get random
   get show_expanded
  },

  },

 'public_contents' => {
    members: %w{},
    collections: %w{
    get _markup_description
    get show_kml_text
  },
  },

  'refs' => {
    members: %w{},
    collections: %w{
    get list_by_author
    get list_recent
    get list_simple
  },
  },

 'repostories' => {
    members: %w{},
    collections: %w{
  },
  },

  'sensus' => {
    members: %w{},
    collections: %w{
    get refs
  },
  },

  'taxon_names' => {
    members: %w{},
    collections: %w{
    get  browse
    get list_by_repository
    get search
    get search_help
    get search_taxon_names
  },
  },

  } # end PUBLIC_RESOURCES

  [PUBLIC_RESOURCES, PRIVATE_RESOURCES].each do |resrc|
    resrc.keys.each do |r|
      resrc[r][:members] = %w{} if resrc[r][:members].nil?
      resrc[r][:collections] = %w{} if resrc[r][:collections].nil?
    end
  end

  mx_resources = {}
  mx_resources = {:private => PRIVATE_RESOURCES, :public => PUBLIC_RESOURCES}

  mx_resources.keys.each do |r|
    mx_resources[r].keys.each do |c|
      scope :projects, :path => "/projects/:proj_id#{r == :public ? "/public" : ''}" do

        resources c.to_sym,
          :controller => (r == :public ? "public/#{c}" : c.to_sym),
          :except => (r == :public ? [:create, :destroy, :edit, :new, :update] : %w{} ) do

          # CAUTION! The following collection and member blocks
          # define actinos available to all public/private resources.
          collection do
            get 'list'
            get "auto_complete_for_#{c}"
          end

          member do
            get "show_figures"
            get "show_tags"
          end

          collection do
            mx_resources[r][c][:collections].each_slice(2) do |rt|
              next if rt.size == 0
              method,action = rt.to_a
              case method
              when 'get'
                get action
              when 'post'
                post action
              else
                raise
              end
            end
          end

          member do
            mx_resources[r][c][:members].each_slice(2) do |rt|
              next if rt.size == 0
              method,action = rt.to_a
              case method
              when 'get'
                get action
              when 'post'
                post action
              else
                raise
              end
            end
          end

        end
      end
    end
  end

  resource :account, :controller => 'account', :only => [] do
    collection do
      get :index
      post :delete
      get :login
      post :login
      get :logout
      get :signup
    end
  end

  resource :admin, :controller => 'admin', :only => [] do
    collection do
      get :debug
      get :eol_dump
      get :index
      get :new_proj
      get :orphaned_images
      get :people_tn
      get :reset_password
      get :stats
      get :title
      post :create_proj
      post :destroy_image
      post :nuke_proj
      post :reset_password
    end
  end

  resources 'association_supports', :controller => 'associations_supports', :only => [] do
    collection do
      post :move
      post :new_ref
      post :new_specimen
      post :new_voucher
    end
  end

  # TODO: remove from above
  resources 'people' do

app/models/pcr.rb
# == Schema Information
# Schema version: 20090930163041
#
# Table name: pcrs
#
#  id            :integer(4)      not null, primary key
#  extract_id    :integer(4)
#  fwd_primer_id :integer(4)
#  rev_primer_id :integer(4)
#  protocol_id   :integer(4)
#  gel_image_id  :integer(4)
#  lane          :integer(1)
#  done_by       :string(255)
#  result        :string(24)
#  notes         :text
#  proj_id       :integer(4)      not null
#  creator_id    :integer(4)      not null
#  updator_id    :integer(4)      not null
#  updated_on    :timestamp       not null
#  created_on    :timestamp       not null
#

class Pcr < ActiveRecord::Base
  has_standard_fields

  include ModelExtensions::Taggable
  include ModelExtensions::Figurable
  include ModelExtensions::DefaultNamedScopes
  include ModelExtensions::MiscMethods

  belongs_to :fwd_primer, :class_name => "Primer", :foreign_key => "fwd_primer_id"
  belongs_to :rev_primer, :class_name => "Primer", :foreign_key => "rev_primer_id"
  belongs_to :confidence
  belongs_to :extract
  belongs_to :protocol
  
  belongs_to :gel_image # TODO: not implemented yet

  has_many :chromatograms, :dependent => :destroy
  has_many :seqs 

  # the possible "genes" tied to this (primers are assigned to a single gene at present, these may be the same -> need to revisit this model at some point)
  has_many :genes, :class_name => 'Gene', :finder_sql => proc {"select distinct g.* FROM genes g
     WHERE g.id IN (SELECT DISTINCT gene_id FROM
    ((SELECT gene_id FROM primers WHERE primers.id = #{rev_primer_id}) UNION
     (SELECT gene_id FROM primers WHERE primers.id = #{fwd_primer_id})) t1) ORDER BY g.id;"}
  
  validates_presence_of :rev_primer
  validates_presence_of :fwd_primer

  # may have to elimiante this
  validates_presence_of :extract 

  scope :by_primer_pair, lambda {|*args| {:conditions => ['fwd_primer_id = ? AND rev_primer_id = ?', (args.first || -1), (args[1] || -1)], :include => [:rev_primer, :fwd_primer, :extract, :seqs]} }
  scope :by_extract, lambda {|*args| {:conditions => ['extract_id = ?', (args.first || -1)]} }
  scope :with_sequence_nucleotides, :include => [:seqs], :conditions => 'length(seqs.sequence) > 0'

  def display_name(options = {})
     @opt = {
      :type => :line # :selected, :list, :list_short
     }.merge!(options.symbolize_keys)
     str = ''
     case @opt[:type]
     when :selected
       str << "id: #{id} - [#{fwd_primer.name} / #{rev_primer.name}]"
       str <<  self.extract.display_name(:type => :selected) 
     when :list
       str <<  self.confidence.open_background_color_span if self.confidence
       str << "id: #{id} - [#{fwd_primer.name} / #{rev_primer.name}]"
       str << '</span>' if self.confidence
     when :confidence
       str <<  self.confidence.open_background_color_span if self.confidence
       str << "#{id}"
       str << '</span>' if self.confidence
     else 
       str << '<div class="dn_' + @opt[:line].to_s + '"'
       str << " style=\"border:2px solid ##{self.confidence.html_color};\"" if self.confidence  
       str << '>' 
       str << "<div>id: #{id} <span class='small_grey'>#{fwd_primer.gene.name} [#{fwd_primer.name} / #{rev_primer.name}] </div>"
       str <<  self.extract.display_name(:type => :sub_select) 
       str << "</div>"
     end
     str
  end

  def otu # :yields: Otu | nil 
   self.extract.otu.class.name == "Otu" ? self.extract.otu : nil
  end

  def gene_name # :yields: String corresponding to the gene name, because gene labels are attached at primer level it's possible for primer pairs to be used with several genes
    [self.fwd_primer.gene.name, self.rev_primer.gene.name].uniq.join("/")
  end

  def gene_name_array # :yields: Array of Gene.name
    [self.fwd_primer.gene, self.rev_primer.gene].uniq
  end

  def self.batch_create(options = {})
    @pcrs = []
    return false if !options[:extract]
    Pcr.transaction do
      begin
        options[:extract].sort.each do |e|
          p = Pcr.new(:extract_id => e[1], :fwd_primer_id => options[:pcr][:fwd_primer_id], :rev_primer_id => options[:pcr][:rev_primer_id], :proj_id => options[:proj_id], :notes => options[:pcr_notes], :protocol_id => ((options[:pcr] && options[:pcr][:protocol_id]) ? options[:pcr][:protocol_id] : nil), :done_by => options[:done_by])
          p.save!
          @pcrs << p
        end
      rescue  #ActiveRecord::RecordInvalid
        raise
      end
    end
    return @pcrs
  end

  def self.find_for_auto_complete(value)
   find_by_sql [
      "SELECT DISTINCT p.* FROM pcrs p
      LEFT JOIN extracts e on e.id = p.extract_id 
      LEFT JOIN primers pf on p.fwd_primer_id = pf.id
      LEFT JOIN primers pr on p.rev_primer_id = pr.id
      LEFT JOIN specimens s on e.specimen_id = s.id
      LEFT JOIN identifiers i ON s.id = i.addressable_id
      LEFT JOIN specimen_determinations sd ON s.id = sd.specimen_id
      LEFT JOIN otus o on o.id = sd.otu_id
      LEFT JOIN taxon_names t ON o.taxon_name_id = t.id 
      LEFT JOIN ces c on s.ce_id = c.id
      LEFT JOIN geogs g on c.geog_id = g.id
      WHERE p.proj_id = #{$proj_id}
      AND (p.id LIKE ? OR
           p.notes LIKE ? OR
           e.id = ? OR
           pf.name LIKE ? OR
           pr.name LIKE ? OR
           e.specimen_id = ? OR
           o.name LIKE ? OR
           o.matrix_name LIKE ? OR
           o.manuscript_name LIKE ? OR
           t.name LIKE ? OR
           (i.cached_display_name LIKE ? AND i.addressable_type = 'Specimen') OR
           sd.name LIKE ? OR
           g.name LIKE ? OR
           c.verbatim_label LIKE ?) LIMIT 40",
       "#{value}", "%#{value.downcase}%", "#{value}", "%#{value.downcase}%",  "%#{value.downcase}%", "#{value}", "#{value.downcase}%", "%#{value.downcase}%", "%#{value.downcase}%", "#{value.downcase}%", "%#{value.downcase}%", "%#{value.downcase}%", "%#{value.downcase}%", "%#{value.downcase}%"]
  end

  def self.default_vol
      {:dntp => 0.5,
       :buffer => 2.5,
       :mg =>  2.0,
       :taq => 0.25,
       :primers => 1.0,
       :templ => 1.5,
       :water => 16.25,
       :rxn_vol => 25,
       :other => 0.0
      } 
  end

end

app/views/seqs/reports/screen/_fasta.html.erb
<div class="text_page" style="font-family:Courier New, monospace">
    <% i = 0 -%>
  <% @genes.each do |g| -%>
  <% @otus.each do |o| -%>
  <% o.sequences(:gene_ids => [g.id]).each do |s| -%>
  <% i = i + 1 -%>
  &gt;<%= s.pcr.andand.extract_id ? "#{s.pcr.extract_id.to_s}_" : ""  -%><%= o.display_name(:type => :matrix_name) -%> <%= g.display_name -%><br />
  <%= display_seq_tag(s) -%><br />
  <% end %>
  <% end %>
  <% end %>
  <%= i == 0 ? content_tag(:em, 'no sequences found') : '' -%>
</div>

app/views/seqs/reports/screen/_grid_summary.html.erb
<h3>Grid summary</h3>
  <%= render :partial => "otuXgene_table" -%>

app/views/seqs/reports/screen/_publication_table.html.erb
<div class="header">Publication table</div>


<!-- header row 1 -->
<div style="border-bottom:1px dotted silver;padding:0.3em;clear:both;"><!-- row -->
  <div style="float:left;width:310px;"><!-- taxal -->
    Taxa
  </div>
  <% @genes.each do |g| %>
    <div style="float:right;width:320px;text-align:center;"><!-- gene col -->
      <%= g.name -%>
    </div><!-- end gene col -->
  <% end -%>
  <br style="clear:both;" /> 
</div>

<!-- header row 2 -->
<div style="border-bottom:1px dotted silver;padding:0.3em;clear:both;"><!-- row -->
  <div style="float:left;"><!-- taxal -->
    <div style="float:left;width:80px;"><!-- family col -->
      Family
    </div>
    <div style="float:left;width:80px;"><!-- subfamily col -->
      Subfamily 
    </div>
    <div style="float:left;width:120px;"><!-- taxon col -->
      Taxon 
    </div>
    <div style="float:left;width:30px;"><!-- taxon col -->
      OTU id 
    </div>
    <br style="clear:both;" />
  </div>
  <% @genes.each do |g| %>
    <div style="float:right;"><!-- gene col -->
      <div style="float:left;"><!-- otu row col -->
        <div style="border-bottom:1px dotted silver;"><!-- seq row  -->
          <div style="float:left;width:60px;"><!-- genbank id -->
            Genbank ID
          </div>
          <div style="float:left;width:60px;"><!-- seq id -->
            mx Seq ID
          </div>
          <div style="float:left;width:200px;"><!-- specimen id -->
            Specimen ID
          </div>
        </div><!-- end seq row -->
        <br style="clear: both;" />
      </div><!-- end otu row -->
      <br style="clear: both;" />
    </div><!-- end gene col -->
  <% end -%>
  <br style="clear:both;" /> 
</div><!-- end otu col -->


<% @otus.each_with_index do |o,i| -%>
  <div style="border-bottom:1px dotted silver;padding:0.3em;clear:both;background-color:<%= (i % 2 == 0) ? '#eee' : 'white' -%>;"><!-- row -->

    <div style="float:left;"><!-- taxal -->

      <div style="float:left;width:80px;"><!-- family col -->
        <%= o.taxon_name.andand.name_at_rank('family') -%>&nbsp;
      </div>
      <div style="float:left;width:80px;"><!-- subfamily col -->
        <%= o.taxon_name.andand.name_at_rank('subfamily') -%>&nbsp;
      </div>
      <div style="float:left;width:120px;"><!-- taxon col -->
        <%= o.taxon_name.andand.display_name -%>&nbsp;
      </div>
      <div style="float:left;width:30px;"><!-- taxon col -->
        <%= link_to(o.id, :action => :show, :id => o.id, :controller => :otus) -%>&nbsp;
      </div>

      <br style="clear:both;" />
    </div>

    <% @genes.each_with_index do |g,j| %>
      <div style="float:right;background-color:<%= (j % 2 == 0) ? '#def' : 'white' -%>;"><!-- gene col -->

        <div style="float:left;"><!-- otu row col -->

          <% o.sequences(:gene_ids => [g.id]).each do |s| -%>
            <div style="border-bottom:1px dotted silver;"><!-- seq row  -->

              <div style="float:left;width:60px;"><!-- genbank id -->
                <%= s.genbank_identifier.blank? ? 'X000000' : s.genbank_identifier -%>
              </div>
              <div style="float:left;width:60px;"><!-- seq id -->
                <%= link_to(s.id, :action => 'show', :controller => 'seqs', :id => s) -%>
              </div>
              <div style="float:left;width:200px;"><!-- specimen id -->
                <%= s.source_specimen.andand.display_name(:type => :identifiers)  -%>
              </div>

            </div><!-- end seq row -->
          <% end -%>

          <br style="clear: both;" />
        </div><!-- end otu row -->

        <br style="clear: both;" />
      </div><!-- end gene col -->

    <% end -%>

    <br style="clear:both;" />
  </div><!-- end otu col -->
<% end -%>